# kubernetes/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-configmap
data:
  config.py: |
    # Django configuration
    DEBUG = False
    ALLOWED_HOSTS = ['*']
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': '/data/db.sqlite3',
        }
    }
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    STATIC_ROOT = '/app/static'
    MEDIA_ROOT = '/app/media'
